# Generated by Django 4.2.22 on 2026-05-17 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('declaracao', '0005_declaracao_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoAssinatura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zapsign_doc_id', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=50)),
                ('signatario_nome', models.CharField(max_length=255)),
                ('signatario_email', models.EmailField(max_length=254)),
                ('arquivo_assinado_url', models.URLField(blank=True, null=True)),
                ('arquivo_assinado_local', models.FileField(blank=True, null=True, upload_to='doumentos_assinados/')),
                ('data_geracao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('declaracao_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='declaracao.declaracao_documento')),
            ],
        ),
    ]
