# Generated by Django 4.2.22 on 2026-04-06 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracao', '0003_declaracao_contrapartida_pesquisa_codigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='declaracao_contrapartida_pesquisa',
            name='data_geracao',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de ção da declaração'),
        ),
    ]
