# Generated by Django 4.2.22 on 2026-05-17 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracao', '0004_alter_declaracao_contrapartida_pesquisa_data_geracao'),
    ]

    operations = [
        migrations.CreateModel(
            name='declaracao_documento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.IntegerField()),
                ('semestre', models.IntegerField()),
                ('mes', models.IntegerField(blank=True, null=True)),
                ('codigo_peia', models.CharField(blank=True, max_length=50)),
                ('nome_projeto', models.CharField(blank=True, max_length=255)),
                ('tipo', models.CharField(choices=[('rh', 'RH'), ('pesquisa', 'Pesquisa'), ('so', 'SO'), ('equipamento', 'Equipamento')], max_length=20)),
                ('caminho_arquivo', models.FileField(upload_to='documentos/')),
                ('nome_arquivo', models.CharField(max_length=255)),
                ('status', models.CharField(default='gerado', max_length=30)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
