# Generated by Django 4.2.22 on 2026-05-17 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('declaracao', '0005_declaracao_documento'),
    ]

    operations = [
        migrations.AddField(
            model_name='declaracao_documento',
            name='id_declaracao',
            field=models.IntegerField(null=True, verbose_name='Declaracao Id'),
        ),
        migrations.AddField(
            model_name='declaracao_documento',
            name='id_projeto',
            field=models.IntegerField(null=True, verbose_name='Projeto Id'),
        ),
    ]
